name: Download Files

on:
  schedule:
    - cron: '*/2 * * * *' # This will run every 5 minutes
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download CHANNELS_URL
      run: |
        curl -o channels $(CHANNELS_URL)

    - name: Download HMAC_URL
      run: |
        curl -o hmac $(HMAC_URL)

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add channels hmac
        git commit -m "Update files from URLs"
        git push
      env:
        CHANNELS_URL: 'https://fox.toxic-gang.xyz/tata/channels'
        HMAC_URL: 'https://fox.toxic-gang.xyz/tata/hmac'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
