name: Download Files

on:
  schedule:
    - cron: '*/2 * * * *' # This will run every 5 minutes
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Set environment variables
      run: |
        echo "CHANNELS_URL=https://fox.toxic-gang.xyz/tata/channels" >> $GITHUB_ENV
        echo "HMAC_URL=https://fox.toxic-gang.xyz/tata/hmac" >> $GITHUB_ENV

    - name: Download CHANNELS_URL
      run: |
        curl -o channels "${{ env.CHANNELS_URL }}"

    - name: Download HMAC_URL
      run: |
        curl -o hmac "${{ env.HMAC_URL }}"

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        git add channels hmac
        git status
        git diff --cached --exit-code || git commit -m "Update files from URLs"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
